### ISSUE TITLE
脚本疑似无法定位页面元素

### ISSUE THREAD

**Issue by Pil0tXia** [SpaceRobot-268369/BJMF_Automation#2]
Traceback (most recent call last):
  File "d:\Automation\BJMF_Automation\BJMF_Auto_v0.6.0.py", line 98, in <module>
    element_03 = wd.find_element_by_xpath('//*[@id="profileform"]/div[3]/div/label[2]')
  File "C:\Users\***\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 514, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\***\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1238, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\***\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Users\***\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="profileform"]/div[3]/div/label[2]"}
  (Session info: headless chrome=96.0.4664.93)
Stacktrace:
Backtrace:
        Ordinal0 [0x00D46903+2517251]
        Ordinal0 [0x00CDF8E1+2095329]
        Ordinal0 [0x00BE2848+1058888]
        Ordinal0 [0x00C0D448+1233992]
        Ordinal0 [0x00C0D63B+1234491]
        Ordinal0 [0x00C37812+1406994]
        Ordinal0 [0x00C2650A+1336586]
        Ordinal0 [0x00C35BBF+1399743]
        Ordinal0 [0x00C2639B+1336219]
        Ordinal0 [0x00C027A7+1189799]
        Ordinal0 [0x00C03609+1193481]
        GetHandleVerifier [0x00ED5904+1577972]
        GetHandleVerifier [0x00F80B97+2279047]
        GetHandleVerifier [0x00DD6D09+534521]
        GetHandleVerifier [0x00DD5DB9+530601]
        Ordinal0 [0x00CE4FF9+2117625]
        Ordinal0 [0x00CE98A8+2136232]
        Ordinal0 [0x00CE99E2+2136546]
        Ordinal0 [0x00CF3541+2176321]
        BaseThreadInitThunk [0x75A16739+25]
        RtlGetFullPathName_UEx [0x774A8FD2+1218]
        RtlGetFullPathName_UEx [0x774A8F9D+1165]

chrome-96-0-4664-93
QQ登录是成功的
似乎前端页面元素没有匹配上
请问有什么头绪吗？

**Comment by tshaveinidea** [comment]
您好，根据以往的经验，大概率是班级魔方后台又修改了，所以一些页面元素也发生了变化，我脚本里使用的是xpath，算是绝对路径，所以后台修改后，我的脚本就会失效。

Lucas

在 2022年9月27日，16:30，Pil0tXia ***@***.***> 写道：

﻿

Traceback (most recent call last):
File "d:\Automation\BJMF_Automation\BJMF_Auto_v0.6.0.py", line 98, in
element_03 = ***@***.***<https://github.com/id>="profileform"]/div[3]/div/label[2]')
File "C:\Users*\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 514, in find_element_by_xpath
return self.find_element(by=By.XPATH, value=xpath)
File "C:\Users*\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1238, in find_element
return self.execute(Command.FIND_ELEMENT, {
File "C:\Users*\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
self.error_handler.check_response(response)
File "C:\Users*\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: ***@***.***<https://github.com/id>="profileform"]/div[3]/div/label[2]"}
(Session info: headless chrome=96.0.4664.93)
Stacktrace:
Backtrace:
Ordinal0 [0x00D46903+2517251]
Ordinal0 [0x00CDF8E1+2095329]
Ordinal0 [0x00BE2848+1058888]
Ordinal0 [0x00C0D448+1233992]
Ordinal0 [0x00C0D63B+1234491]
Ordinal0 [0x00C37812+1406994]
Ordinal0 [0x00C2650A+1336586]
Ordinal0 [0x00C35BBF+1399743]
Ordinal0 [0x00C2639B+1336219]
Ordinal0 [0x00C027A7+1189799]
Ordinal0 [0x00C03609+1193481]
GetHandleVerifier [0x00ED5904+1577972]
GetHandleVerifier [0x00F80B97+2279047]
GetHandleVerifier [0x00DD6D09+534521]
GetHandleVerifier [0x00DD5DB9+530601]
Ordinal0 [0x00CE4FF9+2117625]
Ordinal0 [0x00CE98A8+2136232]
Ordinal0 [0x00CE99E2+2136546]
Ordinal0 [0x00CF3541+2176321]
BaseThreadInitThunk [0x75A16739+25]
RtlGetFullPathName_UEx [0x774A8FD2+1218]
RtlGetFullPathName_UEx [0x774A8F9D+1165]

chrome-96-0-4664-93
QQ登录是成功的
似乎前端页面元素没有匹配上
请问有什么头绪吗？

**Comment by Pil0tXia** [comment]
感谢回复，我知道了，谢谢你的开发

**Comment by tshaveinidea** [comment]
客气，同时天涯苦命人哈哈。

Lucas

在 2022年9月27日，17:25，Pil0tXia ***@***.***> 写道：

﻿

感谢回复，我知道了，谢谢你的开发
